2023-03-22 16:34:55,878 ERROR scheduler Exception in Enqueue Events for Site nandha.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 71, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 110, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 123, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 769, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 515, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 371, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 330, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 196, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1498, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1465, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2023-03-22 16:35:55,976 ERROR scheduler Exception in Enqueue Events for Site nandha.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 71, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 110, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 123, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 769, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 515, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 371, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 330, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 196, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1498, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1465, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2023-03-22 16:39:56,803 ERROR scheduler Exception in Enqueue Events for Site nandha.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 71, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 110, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 123, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 776, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "apps/frappe/frappe/__init__.py", line 1211, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 65, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType System Settings not found

